### ISSUE TITLE
Change package to `org.jetbrains.ringui`?

### ISSUE THREAD

**Issue by CommanderTvis** [mipt-npm/kotlin-ring-ui#1]

**Comment by altavir** [comment]
Nope. It is not JB-official.

**Comment by turansky** [comment]
@CommanderTvis 
One level (simple) package is preferable for declarations.
For example [`react`](https://github.com/JetBrains/kotlin-wrappers/tree/master/kotlin-react/src/main/kotlin) for React (not `com.facebook.react`).

**Comment by CommanderTvis** [comment]
> Nope. It is not JB-official.

Well, `org.khronos.webgl` declarations aren't affiliated with The Khronos Group.

**Comment by turansky** [comment]
Declarations package calculated from NPM package name:
`react` -> `react`
`react-router-dom` -> `react.router.dom`
`@actions/core` -> `actions.core`
`@actions/github` -> `actions.github`

Company name can be excluded, if library name is "uniquely".
`ringui` = JetBtrains Ring UI
`webgl` = ???
